// <auto-generated />
namespace GoBroBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Groups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Groups));
        
        string IMigrationMetadata.Id
        {
            get { return "201601160228259_Groups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
